pizzas/urls.py
"""Defines URL patterns for pizzas."""
from django.conf.urls import url
from . import views
urlpatterns = [
# Home page
url(r'^$', views.index, name='index'),
url(r'^pizza/$', views.pizzas, name='pizzas'),
url(r'^toppings/(?P<idv>[0-9]+)/$', views.toppings, name = 'toppings')
        ]

pizzeria/urls.py
from django.conf.urls import include , url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('pizzas.urls', namespace='pizzas')),
    url(r'', include('review.urls', namespace='review')),
]

review/urls.py
"""Defines URL patterns for reviews."""
from django.conf.urls import url
from . import views
urlpatterns = [
# Home page
url(r'^review/$', views.index, name='index'),
url(r'^review/allreviews/$', views.allreviews, name='allreviews'),
url(r'^review/save reviews/$', views.save_review, name='save_review'),

        ]

pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    """A topic the user is learning about"""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    price = models.FloatField(max_length=200)





class Topping(models.Model):
    """A topic the user is learning about"""
    pizza = models.ForeignKey(Pizza)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

review/models.py
from django.db.models import Avg
from django.db import models

# Create your models here.

class Reviews(models.Model):
    """A topic the user is learning about"""
    review = models.TextField(max_length=200)
    rating=models.IntegerField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def get_reviews(self):
        average =  Reviews.objects.all().aggregate(Avg('rating'))
        allreviews=Reviews.objects.all().order_by('date_added')

        return {'average':average,'reviews':allreviews}

    def save_reviews(self,rating,review):
        save=Reviews(rating=rating,review=review)
        save.save()
        if self.pk == None:
            return 'Your Review Has been Save'
        else:
            return 'Your Review Could not be Saved'

pizzas/views.py
from django.shortcuts import render
from .models import Pizza,Topping

# Create your views here.
def index(request):
    """The home page for Learning Log"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Show all topics."""
    pizza = Pizza.objects.order_by('date_added')
    context = {'pizza': pizza}
    return render(request, 'pizzas/pizza.html', context)

def toppings(request,idv):
    """Show all topics."""

    topping = Topping.objects.filter(pizza_id=idv)
    context = {'topping': topping}
    return render(request, 'pizzas/toppings.html', context)

review/views.py
from django.shortcuts import render
from .models import Reviews
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
def index(request):
    """The home page for Learning Log"""
    return render(request, 'review/index.html')

@csrf_exempt
def save_review(request):
    result = Reviews().save_reviews(request.POST['rating'],request.POST['reviews'])
    context={'result':result}
    return render(request, 'review/confirmation.html',context)


@csrf_exempt
def allreviews(request):
    """The home page for Learning Log"""
    reviews = Reviews().get_reviews()
    context={'reviews':reviews}
    return render(request, 'review/allreviews.html',context)

pizzas/templates/pizzas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pizza Application</title>
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>
 <div class="container-fluid">
     <br>
     <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">MyPizza Admin</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li><a href="{% url 'pizzas:index' %}">Home</a></li>
          <li><a href="{% url 'pizzas:pizzas' %}">Pizza</a></li>

          <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reviews <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'review:index' %}">Post</a></li>
                  <li><a href="{% url 'review:allreviews' %}">All Review</a></li>


                </ul>
              </li>


      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock content %}
 </div>
</body>
</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}
{% block content %}
<p>Welcome to our pizzeria application
, Best Pizza App</p>
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}
{% block content %}
<p>Pizzas</p>
 <ul>
 {% for pizza in pizza %}
  <li><a href="/toppings/{{ pizza.id }}"> {{ pizza.name }}</a></li>
 {% empty %}
<li>No Pizza have been added yet.</li>
 {% endfor %}
 </ul>
{% endblock content %}

pizzas/templates/pizzas/toppings.html
{% extends "pizzas/base.html" %}
{% block content %}
<p>Toppings</p>
 <ul>
 {% for topping in topping %}
  <li>{{topping}}</li>
 {% empty %}
<li>No topping have been added yet.</li>
 {% endfor %}
 </ul>
{% endblock content %}

review/templates/review/allreviews.html
{% extends "pizzas/base.html" %}
{% block content %}

<h2> Average : {{reviews.average.rating__avg}} / 5</h2>
<ul class="list-group">
 {% for reviews in reviews.reviews %}
    <li class="list-group-item">{{reviews.review}} </br>
       Rating: <strong>{{reviews.rating}}</strong> </br> {{reviews.date_added}}</li>

 {% empty %}
<li>No reviews have been added yet.</li>
 {% endfor %}
 </ul>



{% endblock content %}

review/templates/review/confirmation.html
{% extends "pizzas/base.html" %}
{% block content %}
<h2>Thanks for The Rating</h2>
<p>{{result}}</p>
Click <a href="{% url 'review:allreviews' %}">Here</a> to view Ratings

{% endblock content %}

review/templates/review/index.html
{% extends "pizzas/base.html" %}
{% block content %}
<h3>Welcome to our Review application for MyPizza Admin
</h3>


<form class="form-horizontal" action="save reviews/" method="POST">

  <div class="form-group">
    <label for="rating" class="col-sm-2 control-label">Rating</label>
    <div class="col-sm-6">
       <select id="rating" name="rating" class="form-control">
           <option value="1">Very Bad</option>
           <option value="2">Bad</option>
           <option value="3">Good</option>
           <option value="4">Very Good</option>
           <option value="5">Excelent</option>
</select>
    </div>
  </div>
  <div class="form-group">
    <label for="reviews" class="col-sm-2 control-label">Review</label>
    <div class="col-sm-6">
      <textarea id="reviews" name="reviews" class="form-control" rows="5"></textarea>
    </div>
  </div>

    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Save Review</button>
    </div>
  </div>
</form>


{% endblock content %}